name: Log Commit Details

on: [push]

jobs:
  log_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Log commit information
        env:
          TZ: "America/New_York"
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          USER="${{ github.actor }}"
          MESSAGE=$(git log -1 --pretty=%B)
          LOG_ENTRY="${TIMESTAMP}-${USER}-${MESSAGE}"
          
          # Append to workflow.log
          echo "$LOG_ENTRY" >> workflow.log
          
          # If docpage/docs/workflow.md exists, rewrite it with the header and content from workflow.log
          if [ -f "docpage/docs/workflow.md" ]; then
            {
              echo "---"
              echo "prev:"
              echo "  text: \"Map\""
              echo "  link: \"docs/map/map_docs.md\""
              echo "---"
              echo "# Workflow"
              echo
              cat workflow.log
            } > docpage/docs/workflow.md
          fi

      - name: Commit and push log files
        run: |
          git add workflow.log
          if [ -f "docpage/docs/workflow.md" ]; then
            git add docpage/docs/workflow.md
          fi
          git commit -m "Update log files with latest commit details"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
